const Sequelize = require('sequelize')
const dbConfig = require('../config/database')

const Country = require('../app/models/Country')
const Grade = require('../app/models/Grade')
const City = require('../app/models/City')
const HousingType = require('../app/models/HousingType')
const Language = require('../app/models/Language')
const Item = require('../app/models/Item')
const UserType = require('../app/models/UserType')
const Address = require('../app/models/Address')
const Agency = require('../app/models/Agency')
const User = require('../app/models/User')
const ExchangeType = require('../app/models/ExchangeType')
const Exchange = require('../app/models/Exchange')
const Chat = require('../app/models/Chat')
const Message = require('../app/models/Message')
const Favorite = require('../app/models/Favorite')
const Rate = require('../app/models/Rate')
const AgencyGrade = require('../app/models/AgencyGrade')
const ItemRate = require('../app/models/ItemRate')
const ExchangeHousingType = require('../app/models/ExchangeHousingType')
const ExchangeLanguage = require('../app/models/ExchangeLanguage')

const connection = new Sequelize(dbConfig)

Country.init(connection)
Grade.init(connection)
City.init(connection)
HousingType.init(connection)
Language.init(connection)
Item.init(connection)
UserType.init(connection)
Address.init(connection)
Agency.init(connection)
User.init(connection)
ExchangeType.init(connection)
Exchange.init(connection)
Chat.init(connection)
Message.init(connection)
Favorite.init(connection)
Rate.init(connection)
AgencyGrade.init(connection)
ItemRate.init(connection)
ExchangeHousingType.init(connection)
ExchangeLanguage.init(connection)

Country.associate(connection.models)
Grade.associate(connection.models)
City.associate(connection.models)
HousingType.associate(connection.models)
Language.associate(connection.models)
Item.associate(connection.models)
UserType.associate(connection.models)
Address.associate(connection.models)
Agency.associate(connection.models)
User.associate(connection.models)
ExchangeType.associate(connection.models)
Exchange.associate(connection.models)
Chat.associate(connection.models)
Message.associate(connection.models)
Favorite.associate(connection.models)
Rate.associate(connection.models)
AgencyGrade.associate(connection.models)
ItemRate.associate(connection.models)

module.exports = connection
